### ISSUE TITLE
Hmm, nie lepiej to wrzucić do UserProfile? Ale niech ktoś się wypowie

### ISSUE THREAD

**Issue by SzymonKut** [hosu794/juniorstart-backend#38]
Hmm, nie lepiej to wrzucić do UserProfile? Ale niech ktoś się wypowie

_Originally posted by @Ejden in https://github.com/hosu794/juniorstart-backend/pull/32#discussion_r495482915_
.

**Comment by hosu794** [comment]
W sumie dobry pomysł.

**Comment by rmaduzia** [comment]
W pullu B004 jest encja UserProfile, można wtedy tam wsadzić
